# Override default prefix key
# NOTE: C-s I to reload
# NOTE: C-s U to update
set -g prefix C-s

# vim keymaps for tmux pane navigation
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# keymaps for tmux pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# set -g default-terminal "tmux-256color"
# set -ga terminal-overrides ",*256col*:Tc"
set-option -g status-position top

# Tmux Power theme: GitHub Dark High Contrast, minimal
set -g @tmux_power_theme '#71b7ff'
set -g @tmux_power_g0 '#0a0c10'
set -g @tmux_power_g1 '#272b33'
set -g @tmux_power_g2 '#525964'
set -g @tmux_power_g3 '#7a828e'
set -g @tmux_power_g4 '#9ea7b3'
set -g @tmux_power_right_arrow_icon ''
set -g @tmux_power_left_arrow_icon  ''
set -g @tmux_power_left_a  ' #S'
set -g @tmux_power_left_b  ''
set -g @tmux_power_left_c  ''
set -g @tmux_power_left_d  ''
set -g @tmux_power_right_w ''
set -g @tmux_power_right_x ''
set -g @tmux_power_right_y ' %T'
set -g @tmux_power_right_z ' %d-%m-%Y'
set -g @tmux_power_status_interval 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
